/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Pharmacie.Presentation;

import Pharmacie.DAO.GouvernoratDAO;
import Pharmacie.DAO.PharmacieDAO;
import Pharmacie.Entite.Pharmacie;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JDialog;
import javax.swing.JOptionPane;




/**
 *
 * @author SAMSUNG
 */
public class Consultation extends javax.swing.JFrame {

    /**
     * Creates new form Consultation
     */
    private PharmacieDAO pharm=new PharmacieDAO();
    private GouvernoratDAO gouv=new GouvernoratDAO();
    private List<Pharmacie> jTablerempli;
    private  AfficherPharmacies C;
//vriable a utiliser pour tester le filtre
    private boolean livraison=false,cnss=false,infirmerie=false;
    private char jn='j';
    private String gouvernorat="",reg="";
    static boolean acti;
    public Consultation() {
       
        C= new AfficherPharmacies(gouvernorat, reg, jn, infirmerie, cnss, livraison);
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        this.setVisible(true);
    }
    public String[] remplir(String[] s){
        int i=0;
        for(int j=0;j<s.length;j++){
            if(s[j]!=null)
                i++;
        }
        String[] res=new String[i];
        for(int j=0;j<i;j++){
            res[j]=s[j];
        }
        return res;
    }
    public void filtres(){
           
        if(this.chkLiv.isSelected())
            livraison=true;
        else
            livraison=false;
        if(this.chkCNSS.isSelected())
            cnss=true;
         else
            cnss=false;
        if(this.chkInfirm.isSelected())
            infirmerie=true;
         else
            infirmerie=false;
        if(this.chkJN.isSelected())
            jn='n';
        else
            jn='j';
        if(!this.cmbDeleg.getSelectedItem().toString().equals("Tout"))
            gouvernorat=this.cmbDeleg.getSelectedItem().toString();
        else
            gouvernorat="";
        if(!this.cmbReg.getSelectedItem().toString().equals("Tout"))
            reg=this.cmbReg.getSelectedItem().toString();
        else
            reg="";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btHome = new javax.swing.JButton();
        btSuiv = new javax.swing.JButton();
        cmbDeleg = new javax.swing.JComboBox();
        chkCNSS = new javax.swing.JCheckBox();
        chkLiv = new javax.swing.JCheckBox();
        chkJN = new javax.swing.JCheckBox();
        cmbReg = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        btRetour = new javax.swing.JButton();
        chkInfirm = new javax.swing.JCheckBox();
        btValider = new javax.swing.JButton();
        btLocaliser = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Recherche Pharmacie");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        btHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pharmacie/Presentation/home.png"))); // NOI18N
        btHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHomeActionPerformed(evt);
            }
        });

        btSuiv.setText("Suivant");
        btSuiv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btSuivMouseClicked(evt);
            }
        });

        cmbDeleg.setName("cb_delegation"); // NOI18N
        cmbDeleg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbDelegActionPerformed(evt);
            }
        });

        chkCNSS.setText("CNSS");

        chkLiv.setText("Livraison");
        chkLiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkLivActionPerformed(evt);
            }
        });

        chkJN.setText("Pharmacie de Nuit");

        jLabel1.setText("Filtres :");

        btRetour.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pharmacie/Presentation/return.gif"))); // NOI18N

        chkInfirm.setText("Infirmerie");

        btValider.setText("Valider filtre");
        btValider.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btValiderMouseClicked(evt);
            }
        });

        btLocaliser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pharmacie/Presentation/map.gif"))); // NOI18N
        btLocaliser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btLocaliserMouseClicked(evt);
            }
        });
        btLocaliser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLocaliserActionPerformed(evt);
            }
        });

        jLabel2.setText("Région");

        jLabel3.setText("Gouvernorat");

        jTable1.setModel(C);
        this.jTablerempli=C.pharmacies;
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbReg, 0, 122, Short.MAX_VALUE)
                            .addComponent(cmbDeleg, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(chkCNSS)
                    .addComponent(chkLiv)
                    .addComponent(chkJN)
                    .addComponent(jLabel1)
                    .addComponent(chkInfirm)
                    .addComponent(btValider)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btHome, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btRetour, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btLocaliser, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 35, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btSuiv)
                .addGap(48, 48, 48))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btRetour, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btLocaliser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbDeleg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(cmbReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(chkCNSS)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chkLiv)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chkJN)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chkInfirm)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btValider)
                        .addGap(47, 47, 47))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(btSuiv)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btHomeActionPerformed

    private void chkLivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkLivActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkLivActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
 
        this.cmbDeleg.setModel(new javax.swing.DefaultComboBoxModel(gouv.afficherGouvernoratsLabel())); 
        this.cmbReg.setModel(new javax.swing.DefaultComboBoxModel(this.remplir(pharm.findRegionByGouv(""))));
        this.cmbDeleg.insertItemAt("Tout", 0);
        this.cmbDeleg.setSelectedIndex(0);
        this.cmbReg.insertItemAt("Tout", 0);
        this.cmbReg.setSelectedIndex(0);
    }//GEN-LAST:event_formWindowOpened

    private void btLocaliserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btLocaliserMouseClicked
        // TODO add your handling code here:
       if(Map.selection.size()!=0) Map.selection.clear();
       C= new AfficherPharmacies(gouvernorat, reg, jn, infirmerie, cnss, livraison);
       
        this.jTablerempli=C.pharmacies;
        if(this.cmbDeleg.getSelectedIndex()!=0 && gouvernorat!="")
            Map.g=this.gouv.findBylabel(gouvernorat);
        
        if(this.jTable1.getSelectedRow()!=-1)
        { 
          Map.selection.add(this.jTablerempli.get(this.jTable1.getSelectedRow()));
           
        }
        else
        { 

           Map.selection=(ArrayList<Pharmacie>) this.jTablerempli;
        }
        Map m = new Map();
        m.lancer();
    }//GEN-LAST:event_btLocaliserMouseClicked

    private void cmbDelegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbDelegActionPerformed
        // TODO add your handling code here:
        if(!this.cmbDeleg.getSelectedItem().toString().equals("Tout"))  
             this.cmbReg.setModel(new javax.swing.DefaultComboBoxModel(this.remplir(pharm.findRegionByGouv(this.cmbDeleg.getSelectedItem().toString()))));
        else
            this.cmbReg.setModel(new javax.swing.DefaultComboBoxModel(this.remplir(pharm.findRegionByGouv(""))));
        this.cmbReg.insertItemAt("Tout", 0);
        this.cmbReg.setSelectedIndex(0);
    }//GEN-LAST:event_cmbDelegActionPerformed

    private void btValiderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btValiderMouseClicked
        // TODO add your handling code here:
            this.filtres();
         C= new AfficherPharmacies(gouvernorat, reg, jn, infirmerie, cnss, livraison);
         this.jTable1.setModel(C);
         this.jTablerempli=C.pharmacies;
          
    }//GEN-LAST:event_btValiderMouseClicked

    private void btSuivMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btSuivMouseClicked
        // TODO add your handling code here:
      if(this.jTable1.getSelectedRow()!=-1){
         
       Informations.pharmacieInformation= this.jTablerempli.get(this.jTable1.getSelectedRow());
       Informations info=new Informations();
       info.lancer();
       this.setVisible(false);
      }
      else
         JOptionPane.showMessageDialog(this,"Vous devez sélectionner une pharmacie d'abord","Attention!!",JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_btSuivMouseClicked

    private void btLocaliserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLocaliserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btLocaliserActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
         if(Map.acti== true && Map.visi== true )
        {
            JOptionPane.showMessageDialog(this,"Vous devez quitter la page localisation d'abord","Attention!!",JOptionPane.ERROR_MESSAGE);
            
        }
    }//GEN-LAST:event_formMouseClicked

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
       
       
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formWindowClosing

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        if(Map.acti== true && Map.visi== true )
        {
           
            Map.f.setVisible(true);
        }
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Consultation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Consultation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Consultation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Consultation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
     
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               Consultation c = new Consultation();
               
               //c.setVisible(true);
          }
        });
      
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btHome;
    private javax.swing.JButton btLocaliser;
    private javax.swing.JButton btRetour;
    private javax.swing.JButton btSuiv;
    private javax.swing.JButton btValider;
    private javax.swing.JCheckBox chkCNSS;
    private javax.swing.JCheckBox chkInfirm;
    private javax.swing.JCheckBox chkJN;
    private javax.swing.JCheckBox chkLiv;
    private javax.swing.JComboBox cmbDeleg;
    private javax.swing.JComboBox cmbReg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
